# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GTFSagencySelect
                                 A QGIS plugin
 You can choose one or more public transport agencies for routing them in OSM 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-03
        copyright            : (C) 2024 by Luigi
        email                : luigi.dalbosco@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GTFSagencySelect class from file GTFSagencySelect.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GTFSagency_selection import GTFSagencySelect
    return GTFSagencySelect(iface)
